server:
  port: 9100
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AegisLan/config-server/
          search-paths: config-repo
          username: AegisLan
          password: hem2535440



