server:
  port: 9100

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: file://Users/aegis/Documents/Code/Github/cloud-config-repo
          search-paths: /*
          username: AegisLan
          password: hem2535440
          clone-on-start: true
          basedir: /Users/aegis/Documents/Code/local-repo
      label: master


logging:
  level:
    org.springframework.cloud: DEBUG
    org.springframework.boot: DEBUG
